### ISSUE TITLE
Curate the assignee list UI

### ISSUE THREAD

**Issue by joecastro** [huboard/huboard#148]
We have a lot of people who have access to our projects, but there's only a handful who are actively working on it.  It would be great to be able to declare a "core dev team" and only have those avatars appear in the UI for the drag and drop assignments.  A further enhancement with this would be able to categorize multiple teams this way, so I could switch between looking at the dev and test teams.

**Comment by dahlbyk** [comment]
Closing this since the Task/Milestone filter list now only shows users that are currently assigned.
