### ISSUE TITLE
Repository listing didn't show all repos.

### ISSUE THREAD

**Issue by rjmackay** [huboard/huboard#156]
After going to http://huboard.com/ and logging in.
I see most of my repositories but not all. Specifically, I was looking for ushahidi/Lamu but could only see my personal fork rjmackay/Lamu

**Comment by dahlbyk** [comment]
We're using the `/user/repos` endpoint for the primary dashboard screen, sorted by issue count. We will probably revisit the dashboard at some point to improve the experience for users with access to many projects, but for now this is working as intended.
