### ISSUE TITLE
Detect if a full page refresh is needed

### ISSUE THREAD

**Issue by KevM** [huboard/huboard#214]
There are a few scenarios where the state of a given Huboard has the potential to get out of sync with the actual repo. 

Say I have a board up on a tab and walk away and my power settings put my computer to sleep. I am likely missing card moves and what not while my machine is asleep.

**Comment by discorick** [comment]
@rauhryan can this issue be closed?

**Comment by ehausen** [comment]
Well few days ago I had some problems and I created issues:

* Label changes made in Github wont sync without reloading Huboard #564
* Issue created on Github won't sync to Huboard automatically #565

Maybe I don't have this webhook set up? Do I have to do it manually? Doesn't get added when I give Huboard access to my Github?

I just found this issue, so close the others if you feel they are duplicate.

**Comment by ehausen** [comment]
I checked my webhooks and services on Github. 

There seem to be something wrong. How did this happen? How do I fix this?

How can be make it so it doesn't break again, or at least notify when connection is lost.
 
![uploads/0de4a139-8cbe-42ae-ab5f-5b96a9317fbd/Screen Shot 2015-07-03 at 16.11.30.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0de4a139-8cbe-42ae-ab5f-5b96a9317fbd%2FScreen+Shot+2015-07-03+at+16.11.30.png)

![uploads/afc09c5f-e555-4146-a913-1be250327ac3/Screen Shot 2015-07-03 at 16.09.04.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fafc09c5f-e555-4146-a913-1be250327ac3%2FScreen+Shot+2015-07-03+at+16.09.04.png)

**Comment by ehausen** [comment]
Tried many times removing the service, logging in and out..

Real time sync still not working.

Why doesn't the Github service/webhook work? How to reset / install again?

**Comment by discorick** [comment]
@rauhryan  @ehausen We do not yet have full coverage for incoming webhooks from GitHub, specifically we are not yet responding to either issue create, or label changed hooks. They are on the roadmap though!

**Comment by ehausen** [comment]
Alright, but how to rewoke Huboards access, so that my Huboard can sync in real time? :)

Maybe this has something to do with it?
https://developer.github.com/v3/orgs/hooks/
>OAuth applications cannot list, view, or edit webhooks which they did not create.

**Comment by discorick** [comment]
@ehausen, we now have a health checks component that notifies when your board is missing the required webhooks, speaking of which - issue create is now live and issue label/unlabeled hooks are on their way!

**Comment by dahlbyk** [comment]
We're looking to solve this as part of https://github.com/huboard/huboard-web/issues/226

**Comment by discorick** [comment]
Board syncing has been greatly improved, along with the addition of loss of focus (minimize, sleep mode etc.) recovery. Closing.
