### ISSUE TITLE
Check/uncheck task list checkboxes in issue descriptions

### ISSUE THREAD

**Issue by adamralph** [huboard/huboard#255]
GitHub supports task lists with checkboxes in markdown, e.g. https://github.com/config-r/config-r/issues/103

e.g.
- [x] lorem
- [ ] ipsum

See https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments

It would be great if we could check/uncheck those checkboxes from the Huboard issue popup. Currently this requires dropping down to the GitHub issues UI.

**Comment by karlosmid** [comment]
Hi! This feature currently does not work. Regression issue?

**Comment by rauhryan** [comment]
There might be a slight bug if you are NOT the creator of the comment. 

I just tested it and it works if you are the author

**Comment by karlosmid** [comment]
@rauhryan I am the author of the issue. But checkbox is not visible in issue description. You check this feature in huboard preview view?

**Comment by rauhryan** [comment]
it doesn't work in the preview mode. It works once you create the comment

**Comment by karlosmid** [comment]
@rauhryan checked!
Thanks!

**Comment by usman10scorpio** [comment]
- [ usman iqbal] 

- [ ]

**Comment by samshaba** [comment]
[ ]

**Comment by samshaba** [comment]
[]
