### ISSUE TITLE
Sticky Header

### ISSUE THREAD

**Issue by cbrammer** [huboard/huboard#260]
It would be great to have everything above the issues (label headers, milestone header, people, top nav bar) to be sticky at the top of the page. When scrolling through a long list, it makes it very hard to know which column you are moving things into.

Good ui when scrolled all the way to the top:

![screen shot 2013-12-03 at 11 45 15 am](https://f.cloud.github.com/assets/218004/1666716/306f7ce8-5c4b-11e3-8dae-54baa97816f7.png)

Good example of a bad UI when scrolled down the page, which column to drop things onto?

![screen shot 2013-12-03 at 11 45 29 am](https://f.cloud.github.com/assets/218004/1666724/3583628a-5c4b-11e3-8c37-ec205af4749a.png)

**Comment by discorick** [comment]
Closing this in favor of scrolling columns (see https://github.com/huboard/huboard-web/pull/348)
