### ISSUE TITLE
Scroll bar breaks in FF with LOTS of issues

### ISSUE THREAD

**Issue by rauhryan** [huboard/huboard#298]
A user has reported that the scrollbar breaks with a large amount of issues in FF. 

700+ issues 

> It's unbearably slow when trying to work with a repository with 770 issues in its backlog.

> For example, when I click on "Milestones" in Firefox on Linux, it takes 
20 seconds to redraw the page, and while it's doing it there's no visual 
indication that it's working -- the page just hangs. Or when I'm in the 
"Tasks" view and I click the refresh button in my browser, it takes 29 
seconds to redraw the page.

> Dragging and dropping issues to reprioritize them is also quite slow.

> Also, at one point the scrollbar just disappeared and the scroll wheel 
on my mouse stopped working. The only way I could scroll up and down was 
using the Page Up and Page Down keys on my keyboard. Refreshing the page 
fixed this.

**Comment by dahlbyk** [comment]
This isn't specific enough to be actionable. I'm actively using Firefox and will keep an eye out for opportunities to improve.
