### ISSUE TITLE
Want columns with issues side-by-side

### ISSUE THREAD

**Issue by icbat** [huboard/huboard#310]
On the Tasks view:

I've got a ton of things in the backlog column, or sometimes in the to-do column.

I'd like to be able to change a column's width so that two or more issues can sit side-by-side. I'd be fine configuring that in github label if I need to do so.

Might be neat on Milestones too, but I'm more used to those being roughly the same size, where my todo and in-progress are so hugely different that it takes a lot of scrolling.
##

**Comment by dahlbyk** [comment]
Related to https://github.com/huboard/huboard/issues/590
