### ISSUE TITLE
Add list of references on an issue

### ISSUE THREAD

**Issue by gdscei** [huboard/huboard#316]
In GitHub's issue view, you can see where the issue is being referenced (other issues, commits). It would be nice if this was available in HuBoard too.

**Comment by ehausen** [comment]
I think this is a duplicate of #454 which seem to be given a milestone but it is blocked

Maybe you guys can vote there and thsi can be closed?

**Comment by discorick** [comment]
closed by #454

**Comment by dahlbyk** [comment]
Closing in deference to #454
