### ISSUE TITLE
Feature Request: Ability to assign code reviews in issues

### ISSUE THREAD

**Issue by smorin** [huboard/huboard#323]
We work were one team member works on a issue then creates a pull request for it.  Would like the ability to assign code reviews in huboard, then have the people set pull requests as review (accepted, approved, rejected, will not review)

**Comment by dahlbyk** [comment]
I'm going to go ahead and close this in deference to https://github.com/huboard/huboard-web/issues/195. Generally, if you want a "accepted, approved, rejected, will not review" type workflow you're going to want to use a tool like Gerrit.
