### ISSUE TITLE
Add integration for Slack

### ISSUE THREAD

**Issue by jdowning** [huboard/huboard#324]
It would be nice if Huboard could notify Slack of activity (create, update, move, comment). Ideally, this could be realized in an attachment style notification as outlined here:  https://api.slack.com/docs/attachments

Slack seems willing to help out too: https://twitter.com/slackhq/status/456931793472868352 :smile:

**Comment by marcellodesales** [comment]
Is this already available?

**Comment by discorick** [comment]
@marcellodesales You bet - just go to your board and follow settings > integrations

**Comment by marcellodesales** [comment]
@discorick just saw it! Perfect, I will try it...

**Comment by codeyash** [comment]
How to use this? nowhere I can see. No support on slack or Huboard ..what's happenning

Please let us know

-Yash

**Comment by rauhryan** [comment]
![rauhryan_skipping_stones_repo_huboard_and_2__term_screen-256color-bce_tmux__tmux__and_package-puppet__branch__rauhryan_aws-support__and_enterprise-vm__branch__master_](https://cloud.githubusercontent.com/assets/68954/6393936/b3b11db4-bd93-11e4-950e-f785b4d4f68b.png)

**Comment by codeyash** [comment]
I saw that page but couldn't see even there are four buttons. Thanks for quick response. I added and now its working smoothly. 

I like this simple and cool App. Congrats.
