### ISSUE TITLE
Unarchive: toggle show/hide archived tasks

### ISSUE THREAD

**Issue by exalted** [huboard/huboard#340]
As I see it "archiving" feature works basically on closed issues by removing any Huboard label from the related GitHub issue.

I think it would be nice to have a toggle to show or hide archived issues so one could easily "unarchive" issues without going to GitHub web interface and put a label back to it.

What do you think?

**Comment by JudHarris** [comment]
:+1: this just confused me for a few minutes and I was craving a way to see archived issues

**Comment by discorick** [comment]
@exalted @JudHarris, archiving an issue is designed as a mechanism to 'delete' an issue from your HuBoard - but I can see how accidental archives can be annoying and going back to github to erase the 'archived' key is unpleasant UX. 

Still, a toggle or filter to reveal something effectively deleted feels counter-intuitive. I wonder if some "undelete" modal with a list of archived issues (not cards) would be better suited for something like this ?

**Comment by exalted** [comment]
I am terribly sorry for not following up this issue anymore since I am not an active Huboard user since. Best of luck!
