### ISSUE TITLE
Preset the progress status in an ini file so we can reuse it in different repos/set of repos

### ISSUE THREAD

**Issue by patdolem** [huboard/huboard#343]
The goal is to be able to set the progress labels once and be able to reuse them. We have more than 15 products using many repos (about 50 repos) and we need to use the same progress labels for all.

**Comment by rauhryan** [comment]
Reopened via 	28ae99b

**Comment by patdolem** [comment]
@rauhryan This was working for us. What is the problem?

**Comment by discorick** [comment]
Hey @patdolem @rauhryan  , there is a rare bug that can cause the copy to clear out a columns issues - we just wanted to disable this on Saas until we have a proper fix. We _should_ have this addressed before the next HB:E release.

**Comment by dahlbyk** [comment]
Re-closing this now with https://github.com/huboard/huboard-web/pull/249 (allow copy board if the board being copied doesn't have any columns) shipped. This will be in the next enterprise release.
