### ISSUE TITLE
Add deadlines and create an overview

### ISSUE THREAD

**Issue by FinalAngel** [huboard/huboard#362]
It would be really helpful to add a date (deadline) to the tickets and create an overview of your todo's across multiple repositories. Ideally filter this by "today", "this week" or "this month"... as we use GitHub for private and public repos quite heavily.

Currently we have to track the priorities and deadlines using another tool. Most of the tools lack the issue of an overview of open issues.

**Comment by dahlbyk** [comment]
HuBoard is probably not the right tool for this, beyond using Milestones which already support due dates. We're trying to stay very close to data we can represent using GitHub features.

**Comment by FinalAngel** [comment]
thanks for the feedback @dahlbyk – thats alright with me :)
