### ISSUE TITLE
Loading Game for those of us with ADD

### ISSUE THREAD

**Issue by jondavidjohn** [huboard/huboard#381]
at least 75% of the time I load up huboard I get distracted in the time it takes to load...

![squirrel-distraction-add](https://cloud.githubusercontent.com/assets/401520/3936670/ad14b1f6-24a4-11e4-8c7c-7d03f74e6cef.gif)

It would be nice to have something to keep my attention instead of a little spinner wheel, since it can take a long time to load.  Maybe a simple tetris/space invaders clone?

**Comment by dahlbyk** [comment]
We would accept a PR for this. :stuck_out_tongue_winking_eye:
