### ISSUE TITLE
Swimlanes per user

### ISSUE THREAD

**Issue by posix4e** [huboard/huboard#400]
It'd be really useful for us (allow us to get of sprint.ly) if we had a lane per user. That way i can see what people are actively working on
##

**Comment by tottinge** [comment]
Per-user swimlanes are a particularly bad idea.

https://www.industriallogic.com/blog/stop-per-person-swimlanes/
https://www.reddit.com/r/programming/comments/3ahlyu/stop_perperson_swimlanes/

**Comment by rauhryan** [comment]
@tottinge thanks for the articles, I will have to do some more research, but I've alway been on the fence on this issue
