### ISSUE TITLE
Ability to collapse and reorganized types in the filter panel

### ISSUE THREAD

**Issue by patdolem** [huboard/huboard#406]
Collapsing the types (Linked repos, assignment, milestones, and labels) in the filter view would help to avoid scrolling down too much in function of the use priority of the types.
  
It would also be great to be able to reorganize the types in the filter panel. This would help to organize the display in function of the use of these types. For example we use more often the milestone type to filter issues so it should be positioned on top.

**Comment by discorick** [comment]
Collapsible, and reworked order of filters have been added here: https://github.com/huboard/huboard-web/pull/345

Going to close this issue, but if being able to drag and drop filter groups around remains a priority feel free to reopen!

**Comment by patdolem** [comment]
@discorick This is great news. Do you know when it will be available?

**Comment by rauhryan** [comment]
Soon :) We are working on a new enterprise release
