### ISSUE TITLE
Columns can seemingly disappear in Milestones view

### ISSUE THREAD

**Issue by acidix** [huboard/huboard#409]
In the Milestones view, not all milestone will necessarily fit. When that is the case, the extra columns land to the right of the screen, but without any visual hint that not all columns are displayed. No horizontal scroll bar appears and one can only get the extra columns by an un-intuitive click-and-drag mouse gesture..

**Comment by droopy12** [comment]
:+1:

**Comment by dahlbyk** [comment]
Closing in deference to https://github.com/huboard/huboard/issues/452, which has more discussion. Hope to finally have this resolved very soon.
