### ISSUE TITLE
Add ability to specify default templates for new issues

### ISSUE THREAD

**Issue by crertel** [huboard/huboard#436]
It'd be nice to have the "Create new issue..." button also support creating default text in the initial issue message. We use this for making sure feature requests all look the same.

It's a little value-added feature that could fit nicely with Huboard--light enough that I don't feel bad divorcing it from the Github data, but still useful enough to bother with.

I'd imagine this could be a simple account or organization setting that says "Use this default template" and autopopulates when we make a new issue.

**Comment by hiscodeness** [comment]
+1

**Comment by dahlbyk** [comment]
We now support [GitHub Issue Templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)! See https://github.com/huboard/huboard-web/issues/206 and https://github.com/huboard/huboard-web/pull/248 for details.

**Comment by crertel** [comment]
Grarcias.
