### ISSUE TITLE
Add Ruby 2.1.1 stable release tags

### ISSUE THREAD

**Issue by pimpin** [huboard/huboard#443]
Hi, I work in a Ruby 2.1.1 env and Huboard Gemfile is requiring 2.1.2 [since 14th of July](https://github.com/rauhryan/huboard/commits/0709c8acb1e742545bb5ce853adafe887762a781).
[Last stable release tag](https://github.com/rauhryan/huboard/releases/tag/stable) was published the 23th March 2013.... to which commit shall I update it?

**Comment by dahlbyk** [comment]
We're now on Ruby 2.2.1; this seems to no longer be relevant.
