### ISSUE TITLE
Need an horizontal scroll bar for the milestone view

### ISSUE THREAD

**Issue by patdolem** [huboard/huboard#452]
The user experience to view the milestones need to be enhanced. Having many milestones make the navigation difficult. It is necessary to scroll down to the bottom to be able to scroll from right to left or left to right. An horizontal scroll bar should be always visible.

**Comment by droopy12** [comment]
:+1:

**Comment by rauhryan** [comment]
We are currently working on it but ran into a snag with the drag and drop UX

I'm happy to share a screencap of the styling to get some early feedback on our progress

//cc @patdolem

**Comment by rauhryan** [comment]
![rauhryan_skipping_stones_repo_huboard_and_developer_tools_-_http___huboard_local_rauhryan_skipping_stones_repo_and_developer_tools_-_https___trello_com_b_taytf6wa_herp](https://cloud.githubusercontent.com/assets/68954/11123460/85aa98a6-8925-11e5-9fb1-b5f71c1082ea.png)

**Comment by patdolem** [comment]
The styling looks perfect. I like the vertical scroll bar for milestones where all issues are not fitting in the screen.
![thumb-up](https://cloud.githubusercontent.com/assets/5685914/11127448/408ffb9a-8929-11e5-98ce-50c91e93ab91.png)

**Comment by patdolem** [comment]
@rauhryan When this feature will be available. We are eager in getting it. This will help a lot planning our sprints.

**Comment by rauhryan** [comment]
@patdolem we just had a backlog planning meeting and this is one of our top priorities after we have finished our current issues in our Next Release column in HuBoard

https://huboard.com/huboard/huboard

We have 13 issues to get through and then we will be working on a card redesign and the horizontal scrolling issue. 

Can't give you an exact date but we are 100% in development mode right now to get these issues resolved. 

I'll keep you up to date as we make more progress

**Comment by dahlbyk** [comment]
Would we be able to ship the horizontal scroll bar separate from independently-scrolling columns?

**Comment by rauhryan** [comment]
@dahlbyk not really, it's a pretty big and complex change that requires some layout changes and new scrolling logic

**Comment by dahlbyk** [comment]
Our work on this is nearly complete: https://github.com/huboard/huboard-web/pull/280

We'd love some feedback, if anyone can spare some time to kick the tires on our review app: https://huboard-rails-pr-280.herokuapp.com/

**Comment by discorick** [comment]
Hi @patdolem , if you have a few moments https://huboard-rails-pr-280.herokuapp.com/ is about to be shipped - would love any feedback you might have before it makes its way to an enterprise release, Thanks!

**Comment by patdolem** [comment]
@discorick This is cool. It works well and will help a lot.

**Comment by discorick** [comment]
@patdolem Thanks for taking look! We plan to ship today on huboard.com

**Comment by patdolem** [comment]
@discorick It's not yet available on HE:! Do you know when it will be?

**Comment by dahlbyk** [comment]
> @discorick It's not yet available on HE:! Do you know when it will be?

:soon: Keep an eye on https://github.com/huboard/huboard-web/pull/315!
