### ISSUE TITLE
Repo linking is confusing when labels differ

### ISSUE THREAD

**Issue by seanlinsley** [huboard/huboard#481]
I just tried linking two repos together. On one, we have a manually-added `3 - Review` column.

The wording on the page in this scenario is really confusing, and my misreading of it caused all of our Huboard status information to be deleted.

![screen shot 2015-01-19 at 2 53 17 pm](https://cloud.githubusercontent.com/assets/688886/5807726/8c8c221c-9feb-11e4-83c7-1ef77b0e93d4.png)

Note the above screenshot isn't the page where I accidentally deleted our info; it's on the opposite side of the assocation (modernmsg linking ios instead of ios linking modernmsg).

It's really not clear which board is the parent board. Also, it shouldn't be that easy to delete so much data, or at least it should be made clear that that's what is going to happen.

**Comment by rauhryan** [comment]
Oh no! I'm so sorry @seanlinsley, I just realized that we delete labels and then create new ones, which would remove the states of the child boards.

That is not good, so so sorry.

**Comment by dahlbyk** [comment]
We now prevent copying HuBoard labels unless the target board has no HuBoard labels. We may revisit and create a more comprehensive column manager, but for now I believe we adequately guard against the issue you ran into. Sorry, again, for the data loss. :frowning:
