### ISSUE TITLE
Show repo name next to issue number

### ISSUE THREAD

**Issue by phemmer** [huboard/huboard#537]
We have several repos, and multiple repos end up sharing the same color. Even with the color, it is difficult to remember which color goes to which repo.
The solution which makes sense to me is to have the repo name next to the issue number (in task view).

I think this information should also be on the detailed view. When you click an issue and get the modal window, there's nothing in this window which indicates which repo the issue is from.

**Comment by ypaq** [comment]
:+1:

**Comment by mathieumg** [comment]
:+1:

**Comment by dahlbyk** [comment]
Similar to #512

**Comment by rauhryan** [comment]
A wild mockup appears:
![desktop](https://cloud.githubusercontent.com/assets/68954/15971844/cee015e2-2f00-11e6-8848-f36d5052abcc.png)
