### ISSUE TITLE
Issue ordering set in Milestones tab is lost when going back in Tasks tab

### ISSUE THREAD

**Issue by patdolem** [huboard/huboard#543]
After planning and sorting all issues in the Milestones Tab, when going back to Tasks tab the order is lost it is required to re-sort all issues.

**Comment by rauhryan** [comment]
First we set the priority in the backlog view, then we go to the task view. 

Is it possible to have setting to prefer milestone order over task order?

**Comment by jeroentbt** [comment]
I do not understand that question @rauhryan.

I'm in the process of ordering some tasks and also noticed this issue.
Furthermore, if I order them in the tasks window, this sorting order is not taken in to account in the milestones window.

Syncing order from tasks to milestones should be straightforward, no?
Syncing the other way around might be harder.

Let me know if I need to clarify!

**Comment by dahlbyk** [comment]
@rauhryan @discorick Is there a particular reason you guys implemented two separate orderings of issues? I'm tempted to just start ignoring `milestone_order` altogether to focus on preserving relative order of cards in a given column or milestone.

**Comment by discorick** [comment]
Without a separate ordering mechanism on the milestone view, card moves from the task view would create non-sensical ordering on the milestone view (currently). Card order on milestones typically reflect their priority on that milestone, but they can also be in varied stages of completion (backlog, working, review etc.). 

It's proven very difficult to find a comprise that works such that moves are coordinated between views.

**Comment by dahlbyk** [comment]
Clearly not as straightforward as I had thought. It seems reasonable for the Milestone view to give special treatment (i.e. limitations) to cards that have left the first column on the Task board, but I'm not sure what those limitations would need to be to make a single `order` value work.

**Comment by dahlbyk** [comment]
For the record, we're still pondering how to handle the relationship between Milestone and Task ordering.

**Comment by patdolem** [comment]
I don't have this issue anymore. It can be closed.
