### ISSUE TITLE
Master repo vertical line not matching related issues vertical line

### ISSUE THREAD

**Issue by patdolem** [huboard/huboard#549]
The master or main repo (the one that links the other repos) has always a line which is not matching the related issues. In reality, the related issues don't have a vertical line so it should be good not to have the vertical line for the repo. Sometime the same line color is also used by another repo and it is confusing.
The example below shows a blue vertical line for the map_renderer repo while the related issue #56 doesn't have a line.
![master repo vertical line](https://cloud.githubusercontent.com/assets/5685914/7527515/c87ef080-f4d0-11e4-8649-50f5bf0aa998.png)

**Comment by patdolem** [comment]
This is not anymore relevant with HB:E 1.7.155

**Comment by dahlbyk** [comment]
Are you sure? I still see a line on the repo link but not the cards. Are you just saying it no longer bothers you or...?

<img width="325" alt="firefox_2016-10-26_14-48-03" src="https://cloud.githubusercontent.com/assets/133987/19742592/56da1c76-9b8b-11e6-9a69-c9b5588bcd3c.png">

**Comment by patdolem** [comment]
> Are you sure? I still see a line on the repo link but not the cards. Are you just saying it no longer bothers you or...?

Now that the linked repos are indicated in the cards it no longer bother me.
