### ISSUE TITLE
Issues closed by github when merging a PR are not moved to the last column

### ISSUE THREAD

**Issue by stof** [huboard/huboard#598]
According to your blog post http://blog.huboard.com/post/130137307289/end-of-summer-update, issues closed on github should be moved to the final column. but this does not work when the issue is closed by the merge of a pull request. And merged pull requests are not moved there automatically either.

**Comment by kawillia** [comment]
@discorick This is the one we talked about today. Maybe I can find some time over the holiday to fix it up.

**Comment by discorick** [comment]
@kawillia thats awesome! Ping me if you run into any trouble, I was planning to look over this over the weekend as well.

**Comment by rauhryan** [comment]
@discorick can you verify this is still an issue?

**Comment by discorick** [comment]
Confirmed @rauhryan, this is still an issue.

**Comment by dahlbyk** [comment]
Is GitHub firing an event when the issues close? I just happened to close an issue with a PR and the Events API shows separate `PullRequestEvent` and `IssuesEvent` payloads: https://gist.github.com/dahlbyk/c6bf0fe0c4a7f23c5b86

@disckorick do we have an issue somewhere to track that `PullRequestEvent` is not currently being handled?

**Comment by discorick** [comment]
GitHub should be firing issue close events on referenced issue closes, but not on the PR issue itself. As you mentioned the `PullRequestEvent` handles _some_ events for PR issues. 

@dahlbyk do now, https://github.com/huboard/huboard-web/issues/231

**Comment by dahlbyk** [comment]
I'm going to go ahead and close this - I have never seen a PR-closed issue not move as expected. See https://github.com/huboard/huboard-web/pull/255#issuecomment-209232688 for an example that also shows the closing PR move based on new support for PR events.
