### ISSUE TITLE
Huboard removed all labels when syncing new column/label across repos

### ISSUE THREAD

**Issue by benjamincharity** [huboard/huboard#599]
We added a new column/label to one of our repos. In the Huboard settings modal, it asked if we wanted to sync the change across all repos. This sounded like a life-saver so we clicked yes. But then all of our labels were removed and all of our cards were moved to our first column.

First time trying to use that feature, but it seems that it's a bug.

**Comment by discorick** [comment]
This indeed is a bug!  Sorry you got hit by it!

**Comment by dahlbyk** [comment]
As of https://github.com/huboard/huboard-web/pull/249, we now prevent copying HuBoard labels unless the target board has no HuBoard labels. We may revisit and create a more comprehensive column manager, but for now I believe we adequately guard against the issue you ran into. Sorry, again, for the data loss. :frowning:
