### ISSUE TITLE
Need for filtered repo links

### ISSUE THREAD

**Issue by patdolem** [huboard/huboard#601]
Linking a repository should allow label filter.

Let’s say we work in repo 1 and we link in repo 2 which contains a total of 400 issues including 50 labeled with A label. We are not interested in listing the 350 not labeled A.
- If we apply a filter based on A, we will only see the 50 issues in repo 2. And all issues in repo 1 will be filtered out. This is not what we want because we need to prioritize tasks against each other, and if we remove the filter we get all 400 issues from repo 2 which is unmanageable.
- A manual alternative we’re considering now is to add the A label to all issues in repo 1. This implies that we need to always remember to add A label to any new issue and always apply the filter in any view. This could work, but it is not ideal.
- However with the feature we ask for (filtered links) we would create a link to repo 2?label=A and only those 50 features would show up with our main repo 1 board. No need to create extra labels, or always manually apply a label filter to all boards.
Syntax could be:
![filtered link](https://cloud.githubusercontent.com/assets/5685914/10766988/4fecce9a-7c97-11e5-8892-83566ee76900.png)

**Comment by rauhryan** [comment]
:+1: :100: :boom: let's get to work, awesome idea!

**Comment by gutierrezj** [comment]
@rauhryan @discorick it's great to see that you guys are working on this feature! How's it coming along? Also one question: will the filtered link feature also filter out labels, milestones and team members that are not of interest?

**Comment by rauhryan** [comment]
@patdolem @gutierrezj 

This feature is now deployed to production on huboard.com

We will be packaging it up for enterprise very soon. 

RE: 

> Also one question: will the filtered link feature also filter out labels, milestones and team members that are not of interest?

For right now, it only works for labels. We will consider adding milestones and team members later. 

I'd really like to hear a solid use case for why milestones and assignee would be useful, as of now it doesn't seem like a good idea, mainly due to the fact that the GitHub API only allows us to filter on one milestone and one assignee

**Comment by rauhryan** [comment]
Going to close out this issue. Feel free to request a reopen if there is some kind of major issue with the feature.
