### ISSUE TITLE
HuBoard publishes duplicate messages via Slack webhook

### ISSUE THREAD

**Issue by cbeams** [huboard/huboard#608]
We're seeing this sort of thing lately:

<img width="530" alt="screen shot 2015-11-03 at 8 31 56 am" src="https://cloud.githubusercontent.com/assets/301810/10903018/5dd597b2-8205-11e5-904a-cf3c55348b2a.png">

Notice how the last two entries are identical. This is not perfectly reliable, i.e. does not happen every time for any given user, but does happen often enough to wish that it would stop.

**Comment by cbeams** [comment]
Ping. Should I be posting these issues to huboard/huboard-web instead?

**Comment by rauhryan** [comment]
Either repository is acceptable, we link them together in HuBoard :wink:

**Comment by cbeams** [comment]
Just checking in on this issue—We're still seeing these duplicates pretty frequently. Any update? Thanks.

**Comment by discorick** [comment]
@cbeams - sorry about the delay on this, I plan to get to work on it this week!

**Comment by cbeams** [comment]
Great, thanks!

**Comment by seanlinsley** [comment]
Our team has been seeing this for months; I only just now looked for an existing ticket.

**Comment by rauhryan** [comment]
Thanks @seanlinsley 

We are working on it!

Sorry, I'll ping the team and see what I can do

**Comment by discorick** [comment]
I think I found the cause of the double publish bug, this line right here https://github.com/huboard/huboard-web/blob/master/app/jobs/issue_event_job.rb#L30 can return nil on GitHub webhooks, which will cache a key for both the GitHub event and the HuBoard event.

**Comment by dahlbyk** [comment]
> I think I found the cause of the double publish bug, this line right here https://github.com/huboard/huboard-web/blob/8749941acafb54ab45df976557beb0aec3dc5778/app/jobs/issue_event_job.rb#L30 can return nil on GitHub webhooks, which will cache a key for both the GitHub event and the HuBoard event.

It doesn't look like this changed in huboard/huboard-web#255: https://github.com/huboard/huboard-web/blob/d65842ff43a489b750b53673b6964156a979b4f6/app/jobs/issue_event_job.rb#L44

Was the fix something else?

**Comment by rauhryan** [comment]
The assumption was wrong, that class method is only called from a subclass, the lambda gets called not the class method to get the value

**Comment by dahlbyk** [comment]
> The assumption was wrong, that class method is only called from a subclass, the lambda gets called not the class method to get the value

Was ff2e7809cbda8fbabdc673ff714fc1b9db192525 the actual fix? Or 35ad8b369e51d482dd317beee11101013029ff6d? Or do both contribute? Just trying to understand why we think this issue is closed. :grinning:

**Comment by rauhryan** [comment]
It's a combination of setting time stamps, making the key gen overridable, and delaying the execution of the job.

It should be pretty much solved for the most part now

**Comment by haleykoike** [comment]
Has this issue been fixed? We're still consistently seeing duplicated Slack messages when an issue is created. Other Huboard messages don't appear to be duplicated, only issue created ones.

**Comment by dahlbyk** [comment]
> Has this issue been fixed?

We thought so, but apparently not. Thanks for letting us know!

> We're still consistently seeing duplicated Slack messages when an issue is created. Other Huboard messages don't appear to be duplicated, only issue created ones.

We're not able to reproduce with our own Slack notifications, so I'm hoping you can help us narrow in on the potential causes... Do you get duplicates for both issues and PRs? For issues created from HuBoard and from GitHub?

**Comment by dahlbyk** [comment]
It might also help if you add a http://requestb.in/ as a Webhook so we can see if that is also double-publishing. If you don't wish to share here, please send us the link at support@huboard.com, or use the Intercom chat bubble.

**Comment by seanlinsley** [comment]
We're also still seeing duplicates. Scrolling through the chat history, it looks like it's specifically caused by assigning someone and moving that ticket in quick succession.

<img width="520" alt="screen shot 2016-05-16 at 2 07 10 pm" src="https://cloud.githubusercontent.com/assets/688886/15300806/36dd6298-1b70-11e6-9f7c-ade3e8cdd7f2.png">

--------------

<img width="513" alt="screen shot 2016-05-16 at 2 08 03 pm" src="https://cloud.githubusercontent.com/assets/688886/15300808/36ddb9c8-1b70-11e6-9679-194274f09062.png">

--------------

<img width="517" alt="screen shot 2016-05-16 at 2 08 42 pm" src="https://cloud.githubusercontent.com/assets/688886/15300807/36dda1b8-1b70-11e6-93d5-5d6e5adcedb9.png">

--------------

<img width="504" alt="screen shot 2016-05-16 at 2 08 56 pm" src="https://cloud.githubusercontent.com/assets/688886/15300809/36ed3dd0-1b70-11e6-959b-a63e64599bba.png">

**Comment by dahlbyk** [comment]
Are those assignee double-pubs new since Friday? We deployed https://github.com/huboard/huboard-web/pull/297 to fix https://github.com/huboard/huboard/issues/658.

**Comment by seanlinsley** [comment]
This one was on Thursday:

<img width="478" alt="screen shot 2016-05-16 at 6 10 47 pm" src="https://cloud.githubusercontent.com/assets/688886/15306597/ac0cdd20-1b91-11e6-9368-1b0a5449dae2.png">


It also appears that the duplicate notification can happen for issue creation, though that seems to happen less often. Perhaps it's specifically issues created inside Huboard?

<img width="439" alt="screen shot 2016-05-16 at 6 10 23 pm" src="https://cloud.githubusercontent.com/assets/688886/15306618/d4792df4-1b91-11e6-8674-4709ea20bfbe.png">

**Comment by haleykoike** [comment]
@dahlbyk just shared the RequestBin link on Intercom. I added A Github issue on HuBoard and it does look to to double publishing webhooks a few seconds apart.

**Comment by dahlbyk** [comment]
> This one was on Thursday:

@seanlinsley please let us know if duplicate assignment notifications return. We're pretty sure this was a subtle change in the GitHub API response.

> @dahlbyk just shared the RequestBin link on Intercom. I added A Github issue on HuBoard and it does look to to double publishing webhooks a few seconds apart.

Thanks! The two webhook payloads do have subtle differences. It's not immediately obvious to me what the problem is, but @rauhryan or @discorick might see something that sticks out.

```diff
@@ -1,29 +1,20 @@
 {
 	"meta": {
 		"action": "issue_opened",
 		"timestamp": "2016-05-17T00:09:08Z",
-		"correlationId": null,
+		"correlationId": "7ce0cf2e-5317-fcfb-0fd8-af561bfcaaa4",
 		"user": {
 			"login": "haleykoike",
 			"id": 8477004,
 			"avatar_url": "https://avatars.githubusercontent.com/u/8477004?v=3",
 			"gravatar_id": "",
-			"url": "https://api.github.com/users/haleykoike",
-			"html_url": "https://github.com/haleykoike",
-			"followers_url": "https://api.github.com/users/haleykoike/followers",
-			"following_url": "https://api.github.com/users/haleykoike/following{/other_user}",
-			"gists_url": "https://api.github.com/users/haleykoike/gists{/gist_id}",
-			"starred_url": "https://api.github.com/users/haleykoike/starred{/owner}{/repo}",
-			"subscriptions_url": "https://api.github.com/users/haleykoike/subscriptions",
-			"organizations_url": "https://api.github.com/users/haleykoike/orgs",
-			"repos_url": "https://api.github.com/users/haleykoike/repos",
-			"events_url": "https://api.github.com/users/haleykoike/events{/privacy}",
-			"received_events_url": "https://api.github.com/users/haleykoike/received_events",
-			"type": "User",
-			"site_admin": false
+			"site_admin": false,
+			"name": "Haley Koike",
+			"company": "redacted-org",
+			"email": null
 		},
 		"identifier": 32,
 		"repo_full_name": "redacted-org/redacted-repo"
 	},
 	"payload": {
 		"pull_request": null,
@@ -103,13 +94,16 @@
 				"closed_at": null
 			},
 			"comments": 0,
 			"created_at": "2016-05-17T00:09:08Z",
 			"updated_at": "2016-05-17T00:09:08Z",
 			"closed_at": null,
+			"body_html": "",
+			"body_text": "",
 			"body": "\r\n\r\n\u003c!---\r\n@huboard:{\"order\":8.58306884765625e-06,\"milestone_order\":2.3283064365386963e-10}\r\n--\u003e\r\n",
+			"closed_by": null,
 			"current_state": {
 				"url": "https://api.github.com/repos/redacted-org/redacted-repo/labels/0%20-%20Backlog",
 				"name": "0 - Backlog",
 				"color": "CCCCCC",
 				"index": "0",
 				"text": "Backlog",
@@ -123,30 +117,22 @@
 			},
 			"repo": {
 				"owner": {
 					"login": "redacted-org"
 				},
 				"name": "redacted-repo",
-				"full_name": "redacted-org/redacted-repo"
+				"full_name": "redacted-org/redacted-repo",
+				"is_collaborator": true
 			}
 		},
 		"actor": {
 			"login": "haleykoike",
 			"id": 8477004,
 			"avatar_url": "https://avatars.githubusercontent.com/u/8477004?v=3",
 			"gravatar_id": "",
-			"url": "https://api.github.com/users/haleykoike",
-			"html_url": "https://github.com/haleykoike",
-			"followers_url": "https://api.github.com/users/haleykoike/followers",
-			"following_url": "https://api.github.com/users/haleykoike/following{/other_user}",
-			"gists_url": "https://api.github.com/users/haleykoike/gists{/gist_id}",
-			"starred_url": "https://api.github.com/users/haleykoike/starred{/owner}{/repo}",
-			"subscriptions_url": "https://api.github.com/users/haleykoike/subscriptions",
-			"organizations_url": "https://api.github.com/users/haleykoike/orgs",
-			"repos_url": "https://api.github.com/users/haleykoike/repos",
-			"events_url": "https://api.github.com/users/haleykoike/events{/privacy}",
-			"received_events_url": "https://api.github.com/users/haleykoike/received_events",
-			"type": "User",
-			"site_admin": false
+			"site_admin": false,
+			"name": "Haley Koike",
+			"company": "redacted-org",
+			"email": null
 		}
 	}
 }
```

**Comment by dahlbyk** [comment]
I am now able to reproduce this on one of our test repos _almost_ all the time:
<img width="353" alt="slack_2016-05-16_21-24-42" src="https://cloud.githubusercontent.com/assets/133987/15309445/af62c582-1bac-11e6-8be0-6fe70cd70e38.png">

Diff is essentially identical:

```diff
--- C:\Temp\r2.json	2016-05-16 21:21:44.000000000 -0500
+++ C:\Temp\r1.json	2016-05-16 21:21:43.000000000 -0500
@@ -1,29 +1,20 @@
 {
 	"meta": {
 		"action": "issue_opened",
 		"timestamp": "2016-05-17T02:18:12Z",
-		"correlationId": null,
+		"correlationId": "9387fef3-5d2c-781c-f0b6-eb48ce1c8399",
 		"user": {
 			"login": "dahlbyk",
 			"id": 133987,
 			"avatar_url": "https://avatars.githubusercontent.com/u/133987?v=3",
 			"gravatar_id": "",
-			"url": "https://api.github.com/users/dahlbyk",
-			"html_url": "https://github.com/dahlbyk",
-			"followers_url": "https://api.github.com/users/dahlbyk/followers",
-			"following_url": "https://api.github.com/users/dahlbyk/following{/other_user}",
-			"gists_url": "https://api.github.com/users/dahlbyk/gists{/gist_id}",
-			"starred_url": "https://api.github.com/users/dahlbyk/starred{/owner}{/repo}",
-			"subscriptions_url": "https://api.github.com/users/dahlbyk/subscriptions",
-			"organizations_url": "https://api.github.com/users/dahlbyk/orgs",
-			"repos_url": "https://api.github.com/users/dahlbyk/repos",
-			"events_url": "https://api.github.com/users/dahlbyk/events{/privacy}",
-			"received_events_url": "https://api.github.com/users/dahlbyk/received_events",
-			"type": "User",
-			"site_admin": false
+			"site_admin": false,
+			"name": "Keith Dahlby",
+			"company": "HuBoard",
+			"email": "dahlbyk@gmail.com"
 		},
 		"identifier": 51,
 		"repo_full_name": "huboard-testing/spooky-octo-pug"
 	},
 	"payload": {
 		"pull_request": null,
@@ -69,13 +60,16 @@
 			"assignee": null,
 			"milestone": null,
 			"comments": 0,
 			"created_at": "2016-05-17T02:18:12Z",
 			"updated_at": "2016-05-17T02:18:12Z",
 			"closed_at": null,
+			"body_html": "",
+			"body_text": "",
 			"body": "\r\n\r\n\u003c!---\r\n@huboard:{\"order\":1.5272512258763388e-16,\"milestone_order\":7.8580342233181e-09}\r\n--\u003e\r\n",
+			"closed_by": null,
 			"current_state": {
 				"url": "https://api.github.com/repos/huboard-testing/spooky-octo-pug/labels/0%20-%20Backlog",
 				"name": "0 - Backlog",
 				"color": "CCCCCC",
 				"index": "0",
 				"text": "Backlog",
@@ -89,30 +83,22 @@
 			},
 			"repo": {
 				"owner": {
 					"login": "huboard-testing"
 				},
 				"name": "spooky-octo-pug",
-				"full_name": "huboard-testing/spooky-octo-pug"
+				"full_name": "huboard-testing/spooky-octo-pug",
+				"is_collaborator": true
 			}
 		},
 		"actor": {
 			"login": "dahlbyk",
 			"id": 133987,
 			"avatar_url": "https://avatars.githubusercontent.com/u/133987?v=3",
 			"gravatar_id": "",
-			"url": "https://api.github.com/users/dahlbyk",
-			"html_url": "https://github.com/dahlbyk",
-			"followers_url": "https://api.github.com/users/dahlbyk/followers",
-			"following_url": "https://api.github.com/users/dahlbyk/following{/other_user}",
-			"gists_url": "https://api.github.com/users/dahlbyk/gists{/gist_id}",
-			"starred_url": "https://api.github.com/users/dahlbyk/starred{/owner}{/repo}",
-			"subscriptions_url": "https://api.github.com/users/dahlbyk/subscriptions",
-			"organizations_url": "https://api.github.com/users/dahlbyk/orgs",
-			"repos_url": "https://api.github.com/users/dahlbyk/repos",
-			"events_url": "https://api.github.com/users/dahlbyk/events{/privacy}",
-			"received_events_url": "https://api.github.com/users/dahlbyk/received_events",
-			"type": "User",
-			"site_admin": false
+			"site_admin": false,
+			"name": "Keith Dahlby",
+			"company": "HuBoard",
+			"email": "dahlbyk@gmail.com"
 		}
 	}
 }
```

**Comment by dahlbyk** [comment]
This does appear to be specific to issues created from HuBoard. My best guess is that it's related to https://github.com/huboard/huboard-web/pull/286, which was deployed on May 6, but I'm not able to find any duplicates before May 13.

@seanlinsley, @haleykoike, or anyone who wants to help: are you able to trace back when the new issue duplicates first appeared?

**Comment by haleykoike** [comment]
@dahlbyk Looking through my Slack history, the first occurrence we had of a duplicated Slack message on issue creation was May 5, 18:41 UTC. The issue created prior to that on May 2, 11:01 UTC and before did not have duplicate Slack messages.

**Comment by dahlbyk** [comment]
The more holistic fix in https://github.com/huboard/huboard-web/issues/304 was deployed last night. Please let us know if you're still seeing any duplicates!
