### ISSUE TITLE
Support multiple assignees

### ISSUE THREAD

**Issue by cbeams** [huboard/huboard#612]
**Update:** GitHub just added [multiple assignees](https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests) with [API support (preview)](https://developer.github.com/changes/2016-5-27-multiple-assignees/)!

In our development process, we distinguish several roles that can interact with a card throughout its lifecycle. Among them is the idea of a card  "Owner". A card's owner indicates _who is ultimately responsible for getting that card complete_.

Distinct from the owner role, however, we use the card's assignee property to indicate  _who is responsible for the card right now_.

For most of a card's lifecycle, the owner is also the assignee, because it is usually the case that the owner is the developer actually implementing the work for that card.

However, when implementation is complete and the transitions into the `Review` column in HuBoard, we re-assign the card to a designated "Reviewer" who, of course, is always a different developer than the owner/implementer.

This means that by default, owner information is lost when the card is in review. This has led us to track Owner metadata manually in a well-known section of the card description. This works, but is far from ideal. The main problem is that we cannot reliably filter by owner in the HuBoard UI. This means it's hard for folks to track the card's they're ultimately responsible for, which leads to progress getting stuck.

Prior to HuBoard we used LeanKit (and may still return to it). LeanKit supported the concept of "multiple assignees", and while we generally like HuBoard, this is one feature that we really miss.

Is multiple assignees (or indeed multiple distinct "card roles") something that the HuBoard team might consider implementing?

**Comment by cbeams** [comment]
Just checking in here—has this issue been noticed? Any indication of whether this is something the HuBoard team is interested in would be helpful. Not necessarily looking for a commitment—just whether this is something it's reasonable to think _might_ happen.

**Comment by rauhryan** [comment]
Hey @cbeams 

I haven't had time to fully review this request

> has this issue been noticed? 
 
yes

> Any indication of whether this is something the HuBoard team is interested in would be helpful.

not yet

> Not necessarily looking for a commitment—just whether this is something it's reasonable to think might happen.

yes, this is something we would consider adding

---

Multiple assignees is something I'm thinking about, I have some rough ideas on how I would like to see it happen. 

We have a serious limitation for this feature, considering GitHub only supports a single assignee. 

I like the idea of an "owner" and a "reviewer" that could be interesting

I'm also considering supporting, "assignable checklist items" which in a way would surface as a form of multiple assignees

We aren't ready to fully commit to this issue, we still need to have discussions about other ways we might be able to solve it

**Comment by cbeams** [comment]
Thanks. Happy to discuss further. Just let me know how I can help. Appreciate the quick response!

**Comment by rauhryan** [comment]
I'm in the zone @cbeams :stuck_out_tongue_closed_eyes:

**Comment by dahlbyk** [comment]
> Prior to HuBoard we used LeanKit (and may still return to it). LeanKit supported the concept of "multiple assignees", and while we generally like HuBoard, this is one feature that we really miss.

Does LeanKit have the notion of roles for assignees or is it simply a collection of participants? There are interesting things you could do with assigned roles, but it seems like a rabbit hole of complexity that may not align with HuBoard's general simplicity.

One route to take here might be to save a list of "secondary assignees" in the issue metadata (which, being saved in the issue description, would be seen by GitHub as a mention) to bubble up in the UX. We could also support "promoting" a secondary to be the Assignee in GitHub, swapping the previous Assignee back into the secondary list. And finally, the secondary assignees would be considered when filtering the board.

Thoughts?

**Comment by cbeams** [comment]
> Does LeanKit have the notion of roles for assignees or is it simply a collection of participants?

I think it's the latter, but honestly don't remember. In any case...

> There are interesting things you could do with assigned roles, but it seems like a rabbit hole of complexity that may not align with HuBoard's general simplicity.

I agree. I think this is something where the 80% of usefulness (certainly the stuff that would satisfy us) can be handled by a relatively simple approach.

> One route to take here might be to save a list of "secondary assignees" in the issue metadata (which, being saved in the issue description, would be seen by GitHub as a mention) to bubble up in the UX.

+1

We could also support "promoting" a secondary to be the Assignee in GitHub, swapping the previous Assignee back into the secondary list.

+1

And finally, the secondary assignees would be considered when filtering the board.

+1, but this might need to go one step further on the filtering front. We have two main filtering use cases:

 1. As an owner of one or more cards, I want to filter the board in a way that shows me all cards I own regardless of who is currently the primary assignee, so that I can easily tell which cards I am _ultimately responsible for_. This helps me to see if certain cards are "stuck" and if I need to prod the reviewer (secondary assignee) for an update, etc.
 2. As a normal team member, I want to filter the board in a way that shows me all cards I am currently assigned to (primary assignee), so that I can easily tell which cards I am _responsible for doing something with right now_

In case #1 I want the filter to show all cards for which I am the primary or secondary assignee, because I'm the card's _owner_ and so I always care about it.

In case #2, I want the filter to show only the cards for which I am currently the primary assignee, because I want to know what I should take action on right now.

I'm not sure that a generic primary/secondary distinction can satisfy what I'm asking for, but perhaps there's a way. I'm certainly sympathetic to HuBoard's goals around keeping things general and simple, and not going to far "down the rabbit hole" of any one team's specific workflow / roles, etc.

**Comment by dahlbyk** [comment]
GitHub just added [multiple assignees](https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests) with 
[API support (preview)](https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue)!

**Comment by dahlbyk** [comment]
For the record, we are aware that assigning from HuBoard will overwrite all other assignees with the new selection. We'll try to get to this soon to avoid data loss!
