### ISSUE TITLE
Updates to GitHub avatar are not reflected in HuBoard's Slack webhook

### ISSUE THREAD

**Issue by cbeams** [huboard/huboard#614]
I recently changed my GitHub avatar, and this change was immediately visible in HuBoard. Great.

However, messages being posted to Slack via HuBoard continue to use the old avatar. This looks like a caching issue.

**Comment by misterfitz** [comment]
:+1: Would love to have this fixed! @rauhryan

**Comment by discorick** [comment]
This will be fixed with https://github.com/huboard/huboard-web/pull/238 @cbeams @misterfitz

**Comment by dahlbyk** [comment]
I'm honestly not sure why #238 would have fixed this, but it does seem to have:

<img width="236" alt="slack_2016-03-15_22-11-47" src="https://cloud.githubusercontent.com/assets/133987/13800871/05150f0e-eafb-11e5-9e22-76703b4a9b6a.png">

Unless there's something else at play?
