### ISSUE TITLE
Dragging cards to issues with 0 order breaks sorting

### ISSUE THREAD

**Issue by discorick** [huboard/huboard#616]
When dragging cards with either have 0 order, or to columns with cards with 0 order, sorting breaks and cards do not retain their expected position.

**Comment by rauhryan** [comment]
Not trying to be pedantic, but I'd prefer bugs to go into the huboard/huboard-web repository

**Comment by discorick** [comment]
Ah shoot, I mis-clicked the repo in the destination repo drop down. My bad Ill recreate the issue, closing.
