### ISSUE TITLE
Huboard Slack integration - user images always loaded from github.com instead of the github enterprise instance

### ISSUE THREAD

**Issue by gabel** [huboard/huboard#619]
The user icon for webhooks is always resolved from `https://avatars.githubusercontent.com/u/1234?s=64` but if a github enterprise instance is used the icons should load from `https://github.domain.corp/avatars/u/1234?s=64`

For github enterprise users the wrong icons are resolved as their enterprise user id is used to load a user image from github.com with the same user id.

![06-01-2016 10-57-05](https://cloud.githubusercontent.com/assets/242039/12139999/99fbc1b2-b464-11e5-8b2b-2635e389e056.png)

**Comment by misterfitz** [comment]
:+1:

**Comment by dahlbyk** [comment]
Is this related to #614?

**Comment by gabel** [comment]
Not at all. This issue is caused by using the wrong URL to fetch the image. If you have a github enterprise instance the images should be fetch from `ttps://github.domain.corp/avatars/u/1234?s=64` and not from `https://github.domain.corp/avatars/u/1234?s=64`.

**Comment by rauhryan** [comment]
Found where the fix needs to be implemented 

https://github.com/huboard/huboard-web/blob/master/lib/hu_board/services/slack.rb#L32

//cc @huboard/committers

**Comment by dahlbyk** [comment]
@gabel @misterfitz So @rauhryan reminds me that we've probably only solved part of the problem. Is it fair to assume that your avatar URLs won't be accessible to Slack? We could potentially add an Enterprise flag that swaps in a (publicly-available) HuBoard logo instead of Slack trying to resolve user avatars. Thoughts?

**Comment by dahlbyk** [comment]
> We could potentially add an Enterprise flag that swaps in a (publicly-available) HuBoard logo instead of Slack trying to resolve user avatars.

We're trying to get a HB:E release out the door, so we're just going to hard-code a HuBoard avatar for now on Enterprise. @discorick, the image is in #marketing and can live at https://huboard.com/assets/slack/avatar.png or something.

-----

If you're an Enterprise customer and would like something _other_ than a HuBoard logo for your Slack notifications, this would be a good place to vote for your preferred alternative (Gravatar, feature flag to enable GH:E avatars if yours _are_ publicly-accessible, etc).
