### ISSUE TITLE
Total in the column header is always displayed (HB:E)

### ISSUE THREAD

**Issue by patdolem** [huboard/huboard#632]
This happens even when the box in the General settings is unchecked.

**Comment by dahlbyk** [comment]
@patdolem I have not been able to reproduce this after checking several browsers. Are you still seeing this issue? I assume you tried toggling the setting?

**Comment by patdolem** [comment]
@dahlbyk It's not happening anymore so it can be closed.

**Comment by dahlbyk** [comment]
> It's not happening anymore so it can be closed.

:cool:
