### ISSUE TITLE
Filtering by labels with long names has a troublesome UX

### ISSUE THREAD

**Issue by discorick** [huboard/huboard#637]
It can be difficult to identify what filters are active if the labels are exceptionally long. A suggested UX for this on intercom is a display for active filters.

**Comment by ajturner** [comment]
Another for example - filters are added across the top. 

http://catalog.data.gov/dataset?q=charlotte&groups=local&sort=score+desc%2C+name+asc&res_format=Esri+REST

or


![uploads/0469d97e-d528-4e48-9261-fc4d1bbf27cf/Best_Whiskey_-_Reviews_and_Ratings.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0469d97e-d528-4e48-9261-fc4d1bbf27cf%2FBest_Whiskey_-_Reviews_and_Ratings.png)

**Comment by rauhryan** [comment]
:+1:

**Comment by dahlbyk** [comment]
Alternatively, I've been pondering a horizontal "drawer" above the board for filtering (vs sliding in from the side), which would give more horizontal room for long labels.

**Comment by rauhryan** [comment]
Would it be acceptable to set a max-width and truncate with a tooltip?

 - Ryan

**Comment by ajturner** [comment]
I think so - one issue may be long labels with prefixes. How many characters would be visible?

**Comment by ajturner** [comment]
Alternatively, I've been pondering a horizontal "drawer" above the board for filtering (vs sliding in from the side), which would give more horizontal room for long labels

That would exacerbate the large number of labels.

**Comment by dahlbyk** [comment]
Are these labels long enough to produce the undesired behavior?
https://huboard.com/rauhryan/skipping_stones_repo/#/issues/132264941

**Comment by rauhryan** [comment]
confirmed:
![rauhryan_skipping_stones_repo_huboard_and_rauhryan_skipping_stones_repo_huboard](https://cloud.githubusercontent.com/assets/68954/14050207/67078b58-f288-11e5-8e24-2bd08746ac1f.png)

fix included in https://github.com/huboard/huboard-web/pull/250

![rauhryan_skipping_stones_repo_huboard_and_rauhryan_skipping_stones_repo_huboard](https://cloud.githubusercontent.com/assets/68954/14050256/ab7dd9ae-f288-11e5-8c7c-f62fc0808b18.png)

**Comment by discorick** [comment]
@rauhryan nice! What does the extra long label do ? Truncate?

**Comment by rauhryan** [comment]
Handles them pretty gracefully 
![rauhryan_skipping_stones_repo_huboard_and_rauhryan_skipping_stones_repo_huboard](https://cloud.githubusercontent.com/assets/68954/14050918/3515171e-f28d-11e5-98af-5736398bbb84.png)
