### ISSUE TITLE
Can't access a repo owned by a different GH user

### ISSUE THREAD

**Issue by a15a** [huboard/huboard#638]
I'm trying to access REPO owned by ORG by signing on HuBoard with this github account (a15a)

a15a has admin access over REPO, but REPO is owned by ORG, not by a15a

REPO shows up properly on my HuBoard "repositories" page, displaying `ORG / REPO - 88 issues`

When I click on it, the url is huboard.com/ORG/REPO. Visiting it displays a page with the error "HOLD UP! Your subscription for ORG has been canceled!" Note that I'm logged in with a15a, not with ORG.

REPO is private and signing on HuBoard from ORG isn't an option, as there are a bunch of other private repos there that I can't give access to.

It looks like a bug from HuBoard trying to use the user from the url or the target repo, instead of the GH user who's logged in HuBoard?

**Comment by discorick** [comment]
Hey @a15a , I left a more detailed explanation of what's going on via our support channel. Closing this issue.

**Comment by a15a** [comment]
Thanks!

**Comment by dahlbyk** [comment]
Here's the explanation that was provided via support, for others' reference.

> From what I understand you are trying to access a private repository on HuBoard (https://huboard.com/ORG/REPO) with your current User subscription.
>
> When subscribed to a User plan for 'USER' you are effectively unlocking any private repositories in HuBoard that belong to `https://huboard.com/USER/{repo-name}` . Any collaborators on those repositories on GitHub will have the exact same permissions on HuBoard. Similarly in order to gain access to `https://huboard.com/ORG/{repo-name}`, you will need to subscribe for the Organization level plan. I should note this does not extend any permissions greater than are already defined in GitHub. If you have collaborators on one repo and not another, they will only be able to use HuBoards for which they have permission.
>
> I hope this clears things up. If I am right in my assumptions, the best course of action would be for you to visit `https://huboard.com/settings/profile#/ORG` and upgrade to an Organization subscription. If you do not plan on using any private repositories on the 'USER' plan you can feel free to cancel it.
