### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by RicSwirrl** [huboard/huboard#640]
We've managed to persuade a client to use HuBoard to work with us on a project, but they can only use IE11 (their IT policy doesn't allow them to install other browsers). When they log in to the board they don't see any issues (I've reproduced this on a VM running IE11). We've got a paid HuBoard account but this might be a show stopper for us and we may have to use a different tool for this project.

I didn't expect support for old versions of IE, but I kinda expected it to work on the latest version.. 

Is this a known issue? Is it likely to be resolved? I found an old issue from 2012 about IE support but nothing since (https://github.com/huboard/huboard/issues/20).

**Comment by dahlbyk** [comment]
> We've managed to persuade a client to use HuBoard to work with us on a project

Great!

> but they can only use IE11 (their IT policy doesn't allow them to install other browsers)

Sigh.

> Is this a known issue? Is it likely to be resolved?

Yeah, we're reminded of it periodically—even basic support for modern IE is overdue.

It will certainly take some time to work out all the kinks, but just two fixes in I can see and interact with a board. There is hope!
<img width="1034" alt="iexplore_2016-04-01_10-03-02" src="https://cloud.githubusercontent.com/assets/133987/14210941/f5bd3808-f7f0-11e5-8086-951124ce18c9.png">

**Comment by RicSwirrl** [comment]
cool - thanks for picking this up :)

**Comment by dahlbyk** [comment]
@RicSwirrl basic support for IE 11 is now live. I know of scroll/formatting issues with the filter sidebar, but otherwise everything seems to be working as expected. Please have your client give it another try and let us know if there are any other issues!

**Comment by discorick** [comment]
Just noticed this today on Windows 10:

IE 11.212

![uploads/0c575b19-4eb6-4d79-aca0-6aa3da6a1113/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0c575b19-4eb6-4d79-aca0-6aa3da6a1113%2Fblob)

**Comment by dahlbyk** [comment]
@discorick you might check on why it's using Compatibility Mode?

**Comment by rauhryan** [comment]
Fixed with huboard/huboard-web#280
