### ISSUE TITLE
Do not update on Slack when you rearrange issues under a milestone

### ISSUE THREAD

**Issue by jgranick** [huboard/huboard#641]
Hi!

Been trying out HuBoard, liking it so far (particularly for the Milestone tab)

I noticed that in the Slack notifications, we get a notification that "@user changed milestone of repo/repo#1234 to Milestone" each time the sort order is changed. It would be great if these extra messages could be removed, to keep our Slack chat tidier?

Thanks!

**Comment by dahlbyk** [comment]
Thanks for the bug report! We're already trying to avoid this, it's just not quite working. We should be able to ship a fix shortly.

**Comment by dahlbyk** [comment]
Does this card movement/notification align with your expectations?
![milestone-moves](https://cloud.githubusercontent.com/assets/133987/14234213/ad2946a0-f9a2-11e5-8668-165b715827df.gif)

**Comment by dahlbyk** [comment]
@jgranick this fix is live now - please let us know if you have any other issues with notifications (or HuBoard in general)!
