### ISSUE TITLE
Add title and description for a new issue

### ISSUE THREAD

**Issue by jgranick** [huboard/huboard#642]
Hello,

It would be nice if there was a way to add both a title and description to a new issue added on HuBoard. I have been the Milestones view to lay out issues, but I cannot see a way to add a description before the issue is created (I thought maybe shift+enter would do it?)

Our Github is linked to Slack, and when a new issue is created in this format, we get two messages from HuBoard then GitHub, for example:

> jgranick via HuBoard BOT [10:01 PM] 
> @jgranick opened a new issue openfl/openfl#1086
> Re-implement GL masking
> 
> github BOT [10:01 PM] 
> [openfl/openfl] Issue created by jgranick
> #1086 Re-implement GL masking
> \

If I could enter a description, I feel the GitHub notification would be more useful, clarifying the detail on what the issue is, and probably pushing the secret @huboard tag after the fold so it doesn't show in Slack. I know that this is a feature request, but it would really make HuBoard more comfortable to use. Thank you!

**Comment by dahlbyk** [comment]
Clicking on the + button will prompt for more details. I agree that a keyboard shortcut would make sense. For my part, I would expect <kbd>Enter</kbd> to create a simple issue and <kbd><kbd>Ctrl</kbd>-<kbd>Enter</kbd></kbd> to prompt for description (c.f. https://github.com/huboard/huboard-web/pull/257#issuecomment-204782061).

We willl also require a description if you use a [GitHub Issue Template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) once https://github.com/huboard/huboard-web/pull/248 ships.

![create-with-details](https://cloud.githubusercontent.com/assets/133987/14234471/283b9f40-f9a9-11e5-86e5-ef6642666e5a.gif)

**Comment by dahlbyk** [comment]
I'm going to close this - please reopen if I've misunderstood your request.
