### ISSUE TITLE
Ticket refuses to be assigned

### ISSUE THREAD

**Issue by seanlinsley** [huboard/huboard#658]
In Github it'll show someone as having been assigned, with Huboard missing that information despite refreshing.

When attempting to assign someone via Huboard, they're immediately unassigned:

![x30terckf8](https://cloud.githubusercontent.com/assets/688886/15085795/f7475c0e-13a1-11e6-82d7-c33b22a6ca59.gif)

**Comment by discorick** [comment]
Thanks for the bug report! I just tested it out, looks on repeat "assignments" the list starts loosing its mind.

**Comment by rauhryan** [comment]
It's definitely related to webhook events.

So when you change the assignee, it fires an `assigned` && `unassigned` event if you change from one person to another.

If you unassign something completely:

`drusellers` => nothing 

1 event fires
unassigned event payload:

`payload.issue.assignee == null`
`payload.assignee == 'drusellers'`

If you switch assignees

`drusellers` => `rauhryan`

2 events fire
unassigned event payload:

`payload.issue.assignee == 'drusellers'`
`payload.assignee == 'drusellers'`

assigned event payload:

`payload.issue.assignee == 'drusellers'`
`payload.assignee == 'drusellers'`

**Comment by rauhryan** [comment]
As I've been debugging this, I've noticed inconsistent behavior with the GitHub API and their webhook payloads. 

As I'm typing it, I was about to take these notes and file an issue with @github and I think they have fixed the issue before I could even email them

**Comment by rauhryan** [comment]
It's 100% an issue with inconsistent behavior from GitHub, I'll we what I can do to mitigate it, but it's a GitHub bug

**Comment by rauhryan** [comment]
I created a gist with my detailed findings and will submit a ticket to the @github support team. 

https://gist.github.com/rauhryan/6d0f0d1c7f30dd41111c5c77a29dd8ce
