### ISSUE TITLE
Safari scrolling column unexpected behavior

### ISSUE THREAD

**Issue by petey-rock** [huboard/huboard#670]
#### Description:
When using the scrolling column feature in the Safari browser, cards are overlapping and blocking out other cards while dragging a card.
#### Steps to reproduce (if applicable):
Open Safari and go to HuBoard, switch to MileStones view and try dragging a card.
#### Notes:

_contact_ support@huboard.com _for personal support on critical issues_

![uploads/2b4fdbaa-7ce0-46db-bdd2-2e1d97ed696c/Screen Shot 2016-06-02 at 4.44.36 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2b4fdbaa-7ce0-46db-bdd2-2e1d97ed696c%2FScreen+Shot+2016-06-02+at+4.44.36+PM.png)

**Comment by rauhryan** [comment]
Sure enough! 

Dang it, I checked every single browser except safari. 

There is some weird stuff going on in safari!
