### ISSUE TITLE
Feature Request - Please let us filter on items with no assignee

### ISSUE THREAD

**Issue by yaronyg** [huboard/huboard#683]

**Comment by discorick** [comment]
Hi @yaronyg, such a filter already exists! See here: 
![image](https://cloud.githubusercontent.com/assets/1130665/16858484/60bd6a52-49e4-11e6-8f64-854cc5490bc5.png)

**Comment by yaronyg** [comment]
Arg! I was looking at the top because that is where the active members listing is and somehow didn't get my eyes far enough down. Sigh...

**Comment by discorick** [comment]
Ha! No worries, easiest issue I have worked on this week ;) . Makes good online documentation anyways.

**Comment by dahlbyk** [comment]
It's a good point, though, that under "Active members" is a reasonable place to expect the other assignment-based filters. We could move them up to a single line below the avatars: me | others | unassigned.
