### ISSUE TITLE
Tasks Created from Milestone View Don't Use Issue Template

### ISSUE THREAD

**Issue by gbrowne** [huboard/huboard#684]
#### Description:
If you click the `+` button under any milestone in the Huboard milestone view, the *New Issue* dialog does not pre-populate with the issue template text (from `ISSUE_TEMPLATE.md`) like it does when you create an issue from the task view.

#### Steps to reproduce (if applicable):
1. Click *Milestones* in the top right corner
2. Click a `+` button to create a new issue
3. Notice that the issue template text is not pre-populated

#### Helpful external resources (blog, docs, etc.):
N/A

#### Notes:
:notes:

**Comment by dahlbyk** [comment]
> Notes:
> 
> :notes:

Well played.

Not sure how we didn't notice this - thanks!
