### ISSUE TITLE
Issues are unarchived when the assignee is removed from the organization

### ISSUE THREAD

**Issue by rgalanakis** [huboard/huboard#691]
#### Description:

Issues are unarchived when the person they are assigned to is removed from the GitHub organization.
#### Steps to reproduce (if applicable):
- Add a user ("User") to a GitHub Organization, and add User to a Team with access to the private repository housing issues (in our case, we have a CozyCo org, Product team, and a private cozy-sprints repo).
- Create issue
- Assign issue to User
- Move issue to Done column
- Close issue
- Archive issue
- Remove User from Organization
- Observe that the issue is unarchived (the `custom_state` is `""`).

This is super annoying when folks leave since I have to re-archive dozens/hundreds of issues.

**Comment by dahlbyk** [comment]
I'm not able to reproduce this on a private repo in the huboard org.
<img width="529" alt="firefox_2016-09-27_01-30-47" src="https://cloud.githubusercontent.com/assets/133987/18862477/09c2cca8-8452-11e6-9757-8e9e13425d4f.png">

<img width="432" alt="firefox_2016-09-27_01-26-02" src="https://cloud.githubusercontent.com/assets/133987/18862429/b12ecfd8-8451-11e6-8075-da8c58e7bf0e.png">
_remove @dahlbyk-test_
<img width="432" alt="2016-09-27_01-27-48" src="https://cloud.githubusercontent.com/assets/133987/18862422/a82b02e4-8451-11e6-89f3-228a651c33f8.png">

Is there anything else you can think of that may be relevant to the repro? Nothing about removing a user from an organization should result in HuBoard triggering a state change, unless something got out of sync.

**Comment by discorick** [comment]
@rgalanakis , in your reproduction where you able to reliably observe a state change on:

> Archive issue
>    Remove User from Organization
>    Observe that the issue is unarchived (the custom_state is "").

?

It's possible that if you have many older issues that are closed, but were not explicitly "archived" - and that the `last_updated` key is being refreshed when the assignee is being removed. We recently expanded the scope of our closed issues query, and I can imagine a scenario where issues in this situation are bubbling back up.

**Comment by rgalanakis** [comment]
@discorick You are right! I was able to repro this by just unassigning myself from a very old issue. The custom state is still "", but it's now unarchived.

Not sure if your last sentence implies there is a bug, or if this is just an expected side effect, but I'm fine with the current behavior since it's only older issues, so I'm going to close this issue. Thanks for the detective work and explanation!

**Comment by dahlbyk** [comment]
> Not sure if your last sentence implies there is a bug, or if this is just an expected side effect, but I'm fine with the current behavior since it's only older issues

@discorick was referring to https://github.com/huboard/huboard-web/pull/367, which simply fixed that we would show only the first 100 closed (unarchived) issues. An unlikely cause of what you observed, but still potentially related.

While I agree that the current behavior is correct, we could potentially add an additional check to ensure issues closed beyond our two-week window (cc #580) remain hidden even if they get bumped with an update. Maybe not worth it, since strays can simply be archived?

**Comment by rgalanakis** [comment]
Maybe add an 'archive all closed issues' option somewhere? The pain is mostly around having to archive one by one. If we have a sprint with 30 issues, I end up having to archive one by one as well (I mass-close in github itself). Seems like it would be a useful feature in general and provide an easy way to overcome this problem.

**Comment by dahlbyk** [comment]
> Maybe add an 'archive all closed issues' option somewhere?

Agreed. Keep an eye on #542 and #615.
