### ISSUE TITLE
Always proposed the logged in person and the assignee(s) at the top of the assignees list

### ISSUE THREAD

**Issue by patdolem** [huboard/huboard#698]
#### Description:

When a card is opened, it is possible to add/remove assignees through the Assignees list. The list proposed is an alphabetic orders while it should be me, then the name(s) of the already assigned members then the alphabetic order. This is the way it works in GitHub.

#### Notes:

Huboard Enterprise 1.7.150 Release

**Comment by dahlbyk** [comment]
This is partially implemented by https://github.com/huboard/huboard-web/pull/131 but has not been updated for multiple assignees. /cc @kevPo
