### ISSUE TITLE
Please cancel my account and issue a refund for the 8/27 invoice as well

### ISSUE THREAD

**Issue by genejr** [huboard/huboard#713]
#### Description: 
I canceled via your support email on 8/15. Still got billed on 8/27. An email to support@huboard.com yesterday bounced. Are y'all still in business? 

_contact_ support@huboard.com _for personal support on critical issues_

**Comment by rauhryan** [comment]
It appears that my MX records got deleted from my DNS provider. 

Can you please try to send me a support email again. 

> Are y'all still in business?

Yep, still here. Sorry about the trouble
