### ISSUE TITLE
Repository hangs when trying to load

### ISSUE THREAD

**Issue by davidwdonnelly** [huboard/huboard#715]
#### Description:
Last week we suddenly started getting a failure to load our Promys/Promys repository.  We can load other repositories, but this one just hangs.  Here is what we see:

![uploads/1bf82f40-7377-41b0-82ba-909c9aa9cf6b/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1bf82f40-7377-41b0-82ba-909c9aa9cf6b%2Fimage.png)

![uploads/cb374ab8-b09b-46ca-add2-8f40d1144404/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fcb374ab8-b09b-46ca-add2-8f40d1144404%2Fimage.png)

#### Steps to reproduce (if applicable):

![uploads/6a6b2716-7074-426c-842d-65312c83a7a2/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6a6b2716-7074-426c-842d-65312c83a7a2%2Fimage.png)

#### Notes:

_contact_ support@huboard.com _for personal support on critical issues_

This seems to have happened after making a changes to github tickets, but we don't know which ticket and we are not certain that changing the ticket was a cause or just a coincidence.  We don't know how to troubleshoot this, but it is completely blocking us from using Huboard, which is a major inconvenience.

**Comment by rauhryan** [comment]
I think I've fixed the issue. Sorry it took me a while to track it down because I was unable to reproduce the problem on my end. 

increasing the http read timeouts for the GitHub API client seems to have helped. 

https://github.com/huboard/huboard-web/commit/c081aa3b1450ce2434db3ee7b0682f05d170f513

Please let me know if the issue continues

**Comment by davidwdonnelly** [comment]
Ryan:

Thanks for the help, but after several days of hearing nothing back from Huboard support, we were not sure if support was going to look at our problem or not.  As a result, we moved all of our operations to ZenHub.
